modLoader="javafml"
loaderVersion="[30,)" 
issueTrackerURL="http://my.issue.tracker/"
[[mods]]
modId="mineguns"
version="1.0" 
displayName="Mine Guns" 
updateJSONURL="http://myurl.me/" 
displayURL="" 
logoFile="examplemod.png" 
credits="" 
authors="MORIMORI0317,Miyabi0333" 
description='''
This is Ikisugi Guns MOD
'''
